Add branch name check in pm-gh-action & some refactor (#32)
* Add branch name check and workflow level env var

* Update readme for branch name check

* Update pm-gh-action file version

diff --git a/.github/workflows/pm-gh-actions.yml b/.github/workflows/pm-gh-actions.yml
--- a/.github/workflows/pm-gh-actions.yml
+++ b/.github/workflows/pm-gh-actions.yml
@@ -2,7 +2,7 @@
 # Copyright (C) 2021 Prediction Machine Advisers, LLC
 # This file is available under MIT license
 # based on https://github.com/predictionmachine/pm-gh-actions/blob/main/.github/workflows/pm-gh-actions.yml
-# version 0.3.1
+# version 0.3.2
 ############################################################################################
 
 name: PM CI workflow
@@ -20,13 +20,48 @@ on:
     branches:
       - main
       - dev
+env:
+  GUIDELINE_REPO: 'https://github.com/predictionmachine/pm-coding-template'
+
 jobs:
+
+  # Check branch name standard as per `pm-coding-template`
+  # Ref: https://github.com/predictionmachine/pm-coding-template#github-branches-pull-requests
+  check-branch-naming-convention:
+    runs-on: ubuntu-latest
+    name: Check branch naming convention as per `pm-coding-template`
+    if: ${{ github.event_name == 'pull_request' }}
+    env:
+      BRANCH_NAME_RULE: 'https://github.com/predictionmachine/pm-coding-template#github-branches-pull-requests'
+    steps:
+      - name: Check branch name
+        id: branchCheck
+        run: |
+          echo "branch name: $GITHUB_HEAD_REF"
+          if [[ "$GITHUB_HEAD_REF" =~ "/" ]];then
+            echo "::set-output name=is_valid_name::true"
+          else
+            echo "::set-output name=is_valid_name::false"
+          fi
+      - uses: marocchino/sticky-pull-request-comment@v2
+        if: ${{ steps.branchCheck.outputs.is_valid_name == 'false' }}
+        with:
+          header: invalid-branch-name-comments
+          message: |
+            👋 &nbsp; @${{ github.event.pull_request.user.login }}
+            Please use the valid branch name, [see here](${{ env.BRANCH_NAME_RULE }}).
+            Please make sure you have followed our [contributing guidelines](${{ env.GUIDELINE_REPO }}).
+      - name: Exit job for invalid branch name
+        if: ${{ steps.branchCheck.outputs.is_valid_name == 'false' }}
+        run: |
+          echo "Invalid branch name: $GITHUB_HEAD_REF"
+          echo "Please use the standard mentioned here: ${{ env.BRANCH_NAME_RULE }}"
+          exit 1
 
   enforce-pr-description:
     runs-on: ubuntu-latest
     name: 'Check PR description, fail if empty'
     env:
-      GUIDELINE_REPO: 'https://github.com/predictionmachine/pm-coding-template'
       TEMPLATE_URL: 'https://github.com/predictionmachine/pm-coding-template/blob/main/.github/pull_request_template.md'
     steps:
       - name: Check PR description
@@ -60,7 +95,7 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v2
       - name: 'Check if file exists, and set flag'
-        id: file_check
+        id: fileCheck
         run: |
           file_count=$(find ./ -type f \( -iname \*.zip -o -iname \*.parque \) | wc -l ) # get file count of the unwanted files
           if [[ "$file_count==0" ]];then
@@ -73,13 +108,13 @@ jobs:
             exit 0
           fi
       - uses: marocchino/sticky-pull-request-comment@v2
-        if: ${{ steps.file_check.outputs.is_unwanted_file == 'true' }}
+        if: ${{ steps.fileCheck.outputs.is_unwanted_file == 'true' }}
         with:
           header: file-check
           message: |
             👋 &nbsp; @${{ github.event.pull_request.user.login }}
             Please remove unwanted files from the repo.
-            Here is the detected file path: ${{ steps.file_check.outputs.file_paths }}
+            Here is the detected file path: ${{ steps.fileCheck.outputs.file_paths }}
             Please make sure you have followed our [contributing guidelines](${{ env.GUIDELINE_REPO }}).
 
   # see [reviewdog/action-detect-secrets](https://github.com/Yelp/detect-secrets) and
